name: Python auto tests

on: 
  workflow_dispatch:
    inputs:
      deployment_target:
        description: choose tests set
        required: true
        type: choice
        default: smoke
        options:
          - smoke
          - regression
          - all

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run autotests
    steps:
      - name: Checkout autotests
        uses: actions/checkout@v4

      - name: set up Python environment
        uses: actions/setup-python@v4
        with: 
          python-version: "3.12"

      - name: install dependencies
        run: pip install -r requirements.txt

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '17'

      - name: Install Allure
        run: |
          wget https://github.com/allure-framework/allure2/releases/latest/download/allure-2.30.0.zip
          unzip allure-2.30.0.zip -d /opt/
          export PATH=$PATH:/opt/allure-2.30.0/bin

      - name: run regression tests
        if: "github.event.inputs.deployment_target=='regression'"
        run: pytest -v -m regression --alluredir=allure-results tests/test_elements.py
        continue-on-error: true

      - name: run smoke tests
        if: "github.event.inputs.deployment_target=='smoke'"
        run: pytest -v -m smoke --alluredir=allure-results tests/test_elements.py
        continue-on-error: true

      - name: run all tests
        if: "github.event.inputs.deployment_target=='all'"
        run: pytest -v --alluredir=allure-results tests/test_elements.py
        continue-on-error: true

      - name: Generate test report
        run: allure generate allure-results -o allure-report

      - name: Upload Allure Report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report
          retention-days: 1
